#!/bin/sh

# Arguments - upstream calligra-l10n tarballs
#
# Script needs to be called from calligra-l10n/ folder, i.e.:
# ./debian/upstream2orig ../path/to/upstream/src/folder/calligra-l10n/*
#
#

PREFIX="calligra-l10n"

get_orig_name() {
    local tarball upstream
    local lang version

    tarball="$1"
    upstream=`basename "$tarball"`
    lang=${upstream#${PREFIX}-}
    lang="${lang%.tar.xz}"

    version=${lang#*-}
    lang="${lang%%-*}"
    lang="`echo $lang | tr -d _@ | tr A-Z a-z`"
    echo "${PREFIX}_${version}.orig-${lang}.tar.xz $lang"
}

extract_tarball() {
    local lang="$1"
    local orig="$2"

    rm -rf "$lang"
    mkdir "$lang"
    tar xJf "$orig" --strip=1 -C "$lang"
}

orig=""
while [ -n "$1" ]; do
    if [ "${1#*.orig*}" != "$1" ]; then
        # Tarball already has orig in its name. Just extract
        echo "Extracting tarball $1 ..." >&2
        lang="${1##*.orig-}"
        lang="${lang%%.tar.xz}"
        extract_tarball "$lang" "$1"
    else
        echo "Renaming and extracting tarball $1 ..." >&2
        orig="../`get_orig_name "$1"`"
        lang=${orig#* }
        orig=${orig% *}
        rm -f "$orig"
        ln -f "$1" "$orig"
        extract_tarball "$lang" "$orig"
    fi
    shift
done
